# Generated by Django 5.2.3 on 2025-07-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readpdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=1200, unique=True),
        ),
    ]
